language: node_js
node_js:
  - '8'
services:
  - docker
install:
  - yarn --ignore-engines
  - docker pull bitnami/cassandra:latest
  - yarn test
  - yarn build
  - docker build -t turbologz/turbo-logz-applications-api:$TRAVIS_BUILD_NUMBER .
deploy:
  - provider: script
    script: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" && docker push turbologz/turbo-logz-applications-api
    on:
      branch: master